version: '3.9'

services:
    mysql:
      image: mysql:latest
      container_name: db-shopper
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: password
      cap_add:
        - SYS_NICE